const database = [
    // {Dname : '김채원', name : 'sogeun sogeun', preimage : "img/소근소근.png", sub_title: '어시스턴트 기능으로 쉽게 하는 <br> 1인 오디오 방송 어플', text : '<h4>코로나 시대가 지속되면서 비대면 활동과 SNS을 통한 소통이 증가했습니다.</h4>' , backgroundImage : 'img/background.png', video : "https://www.youtube.com/embed/1rY6twRCdzo", profileImage : "img/designer/designer1.jpg" , say : "아이디어가 반짝이는 디자이너가 되도록 노력하겠습니다." , Email : "wksehs123@naver.com"},
    {Dname : '이송백', 
    name : 'LEAVE-OUT', 
    preimage : "img/preview/preview1.jpg", 
    sub_title: '[LEAVE-OUT]은 현 전기자동차 배터리의 고질적 문제를 친환경적 방식으로 해결하면서,성능 및 유지를 극대화 하기 위한 운송기기입니다.', 
    text : '<h4>전기자동차 배터리의 고온 화재와 저온 성능감소가 문제로 대두되고 있습니다.</h4>' , 
    backgroundImage : 'img/background/background1.jpg', 
    video : "https://www.youtube.com/embed/1rY6twRCdzo", 
    profileImage : "img/designer/designer1.jpg" , 
    say : "풍부한 조형의 아름다움을 전달하는 디자이너가 되고자 합니다. 미래 도시 환경의 분위기를 주도하는 자동차를 디자인해 사람들을 만족시키는 것이 꿈입니다.", 
    Email : "wksehs123@naver.com"},

    {Dname : '김신일', 
    name : 'AR Display', 
    preimage : "img/preview/preview2.jpg", 
    sub_title: '운전중 기존 네비게이션으로 쏠리는 시야를 전방으로 향하게끔하여 운전중 언제든 전방을 주시할 수 있게끔 합니다.', 
    text : '<h4>운전중 운전자의 시선의 50%가 전방외의 시선을 둔다는데 100% 전방을 주시하게 할 수 없을까?</h4>' , 
    backgroundImage : 'img/background/background2.jpg', 
    video : "https://www.youtube.com/embed/WUWQllO4jQk", 
    profileImage : "img/designer/designer2.jpg" , 
    say : "내가 하고 싶은 디자인을 하는 것이 목표입니다", 
    Email : "wksehs123@naver.com"},

    {Dname : '조재희', 
    name : 'PLUG', 
    preimage : "img/preview/preview3.jpg", 
    sub_title: '주행 중 운전자의 휴식을 위한 졸음쉼터가 스마트 복합 쉼터로 변경됩니다. 쉼터가 신설됨에 따라 주차 시, < PLUG >은 차량으로 스스로 이동, 운전자의 추가적인 이동 없이도 배터리를 쉽고 간편하게 가능하도록 도와줍니다.', 
    text : '<h4>전기차 수요의 증가에 따라 배터리와 주행 시간에 대한 중요도 또한 높아졌습니다.</h4>' , 
    background:"sad", backgroundImage : 'img/background/background3.jpg', 
    video : "https://www.youtube.com/embed/WUWQllO4jQk", 
    profileImage : "img/designer/designer3.jpg" , 
    say : "스스로 만족하는 디자인을 하는 디자이너가 되고 싶습니다.", 
    Email : "wksehs123@naver.com"},

    {Dname : '김정연 이윤하', 
    name : 'Cambio Tire', 
    preimage : "img/preview/preview4.jpg", 
    sub_title: '아파트 단지 내 고도가 낮은 지하주차장 이용이 어려운 택배차에 적용하는 가변형 타이어입니다. 캄비오 타이어는 타이어의 면적이 넓어지고 좁아지면서 차고의 높낮이를 조절할 수 있도록 도와줍니다.', 
    text : '<h4>교통사고 감소를 위한 "차 없는 단지" 조성 아파트 출현</h4>' ,
    background:"sad", 
    backgroundImage : 'img/background/background4.png', 
    video : "https://www.youtube.com/embed/WUWQllO4jQk", 
    profileImage : "img/designer/designer3.jpg" , 
    say : "다시한번 뒤돌아 보며 다시 생각나는 작품을 고민하는 디자이너가 되고자 합니다. 모두가 만족 할 수 있는 디자인을 만드는 것이 저의 꿈입니다.", 
    Email : "wksehs123@naver.com"},

    {Dname : '김현담', 
    name : 'ERT', 
    preimage : "img/preview/preview6.jpg", 
    sub_title: '이알티는 전기동력을 사용한 경운기로 도로주행시 핸들을 논작업시 작업핸들을 사용하여 사용자의 편의성을 극대화할 수 있습니다', 
    text : '<h4>전기경운기는 친환경적이고 사용자의 안전을 최우선으로 고려된 경운기입니다.</h4><p>기존 경운기의 내연기관에 따른 여러가지 문제점이 제기되고 변화가 필요한 상황임에도 경운기는 60년동안 변화가 거의 없었습니다. 따라서 귀농청년들과 전기트랙터가 등장함에 따라서 경운기도 트랜드에 따라 변화해야합니다.<p/>', 
    background:"기존 경운기의 내연기관에 따른 여러가지 문제점이 제기되고 변화가 필요한 상황임에도 경운기는 60년동안 변화가 거의 없었습니다. 따라서 귀농청년들과 전기트랙터가 등장함에 따라서 경운기도 트랜드에 따라 변화해야합니다.", 
    backgroundImage : 'img/background/background6.jpg', 
    video : "https://www.youtube.com/embed/WUWQllO4jQk", 
    profileImage : "img/designer/designer6.jpg" , 
    say : "사람의 마음을 움직이는 디자인을 하고자 합니다.", 
    Email : "wksehs123@naver.com"},

    {Dname : '팜칸린', 
    name : 'MotorTiller', 
    preimage : "img/preview/preview7.png", 
    sub_title: '오토바이를 이용하는 경작기 는 베트남에서 경제적인 측면에 어려움을 겪는 농민들을 위해 농사일 혹은 밭갈이에 시간, 체력과 돈을 절약하는 데에 도움을 주는 제품입니다.', 
    text : '<h4>베트남 농민들이 밭을 갈 때 시간과 체력이 많이 소요되며, 농기구가 있어도 불편한 점이 많습니다.</h4>' , 
    background:"베트남 인구 중에 농민 인구가 많지만 농사일에 다수 자동 농기구나 전기 농기구를 사용하지 않고 사람의 힘을 쓰고 합니다. 특히 밭을 갈기에 시간과 체력이 많이 소요되며, 경작기를 사용해도 사람이 직접 끌고 해야 하기 때문에 불편과 피로를 줄 수도 있습니다. 체력과 시간을 절약하면서 경제적 측면에 여유가 없는 농민들의 환경에 맞춰줄 수 있는 저비용 고효율의 경작기가 필요합니다.", 
    backgroundImage : 'img/background/background7.png', 
    video : "https://www.youtube.com/embed/IjmQgYf5RI8", 
    profileImage : "img/designer/designer7.jpg" , 
    say : "한국에서 유학해 온 베트남 디자이너로서 사람한테 유용한 멋진 디자인을 하고 싶습니다. 사회 발전에 조금이라도 기여할 수 있었으면 한다는 꿈이 있습니다.", 
    Email : "wksehs123@naver.com"},

    {Dname : '허지연', 
    name : 'ROADY', 
    preimage : "img/preview/preview8.png",
    sub_title: '< ROADY >는 사용자와 에이전트와의 커뮤니케이션을 통해 차량과 사용자를 연결하며, 개인화된 차량 이용 데이터의 활용을 통해 사용자의 공유 차량 이용 경험을 자연스럽게 연결해줄 수 있는 서비스를 제공합니다.', 
    text : '<h4>공유 경제 시대로 변함에 따라 공유 차량 시장도 큰 주목을 받고 있습니다.</h4>' , 
    background:"최근 소비 형태가 소유의 개념에서 경험의 개념으로 변화함에 따라, 제품과 서비스를 구매하는 대신 일시적으로 공유하기 위해 비용을 지불하는 소비자가 점점 늘어나고 있습니다. 공유경제로의 소비 형태가 변화함에 따라, 대표적으로 차량 업계에서도 차를 개인이 소유하는 것이 아닌 한 대의 차를 여러 사람이 공유하여 사용하는 카쉐어링 서비스가 주목을 끌고 있습니다. 차량 공유 시장은 재화적 가치뿐만 아니라 여러 환경적인 문제에서도 긍정적인 영향을 끼칠 수 있어 전 세계적으로 공유 차량 시장을 활성화하기 위한 노력이 급증하고 있습니다.", 
    backgroundImage : 'img/background/background8.png', 
    video : "https://www.youtube.com/embed/zb_VoSy5vfA", 
    profileImage : "img/designer/designer9.jpg" , 
    say : "디자인을 통해 우리의 일상 속에 자리하고 있는 모든 문제점에 대한 개선안을 고민하여, 저의 디자인으로 하여금 모두가 편리하고 유연한 일상을 경험할 수 있도록 하는 것이 저의 목표입니다.", 
    Email : "wksehs123@naver.com"},
    
    {Dname : '백승렬', 
    name : 'CHARGE GO', 
    preimage : "img/preview/preview5.png", 
    sub_title: '전기차를 위한 전기차 전용 배터리 트레일러 < CHARGE GO >는 전기차의 주행거리 문제와 충전 인프라 문제 두 가지를 동시에 해결할 수 있는 제품입니다.', 
    text : '<h4>전 세계적으로 ‘탈 내연기관’ 흐름의 가속화로 전기차의 판매량은 증가하고 있습니다.</h4> <p>전 세계적으로 "탈 내연기관" 흐름의 가속화로 전기차의 판매량은 엄청나게 증가하고 있지만, 전기차의 고질적인 주행거리 문제와, 증가하는 전기차의 등록대수에 비해 매우 부족한 충전 인프라 문제가 현재까지 제기되고 있습니다. 그래서 이와 같은 문제들을 해결하기 위해서 트레일러 형식의 배터리를 디자인했습니다.<p/>' , 
    background:"복잡한 공항에서 정수기나 물을 구할 곳을 찾아다녀야 하는 번거로움과 보안 검색대를 지나는 과정에서 다 마시지 못한 생수통이 버려지는 문제는 공항 이용객들에게 불편함을 초래합니다. 팬데믹 이후 공항 이용률이 증가하고 있는 현재, 앞선 문제를 해결하며 공항 이용객의 편의를 향상할 수 있는 새로운 서비스가 필요합니다. 그래서 우리는 갈증을 해소함과 동시에 공항 이용객이 물을 찾아 헤매는 번거로움을 줄일 수 있는 자율주행 물 제공 서비스 로봇을 만들게 되었습니다. 이 제품은 한 모금의 물을 활용하여 간편하게 고객의 니즈를 충족시킬 수 있는 대안을 담고 있습니다.", 
    backgroundImage : 'img/background/background5.jpg', 
    video : "https://www.youtube.com/embed/aRJSC3eOJCI", 
    profileImage : "img/designer/designer5.jpg" , 
    say : "상상을 현실로 만드는 디자이너가 되고 싶습니다.", 
    Email : "wksehs123@naver.com"},

    {Dname : '이경석', 
    name : 'CAPTAIN', 
    preimage : "img/preview/preview9.jpg", 
    sub_title: '자율주행 물 제공 서비스 로봇인 "CAPTAIN"은 공항 이용객의 갈증을 해소하며, 보안 검색대를 지나는 과정에서 버려지는 플라스틱 생수통과 그 안에 남아있던 물이 버려지는 것을 방지하기 위해 고안된 제품입니다.', 
    text : '<h4>공항 보안 검색대를 지나며 수많은 플라스틱 생수통이 버려지고 있습니다.</h4><p>복잡한 공항에서 정수기나 물을 구할 곳을 찾아다녀야 하는 번거로움과 보안 검색대를 지나는 과정에서 다 마시지 못한 생수통이 버려지는 문제는 공항 이용객들에게 불편함을 초래합니다. 팬데믹 이후 공항 이용률이 증가하고 있는 현재, 앞선 문제를 해결하며 공항 이용객의 편의를 향상할 수 있는 새로운 서비스가 필요합니다. 그래서 우리는 갈증을 해소함과 동시에 공항 이용객이 물을 찾아 헤매는 번거로움을 줄일 수 있는 자율주행 물 제공 서비스 로봇을 만들게 되었습니다. 이 제품은 한 모금의 물을 활용하여 간편하게 고객의 니즈를 충족시킬 수 있는 대안을 담고 있습니다.<p/>', 
    background:"복잡한 공항에서 정수기나 물을 구할 곳을 찾아다녀야 하는 번거로움과 보안 검색대를 지나는 과정에서 다 마시지 못한 생수통이 버려지는 문제는 공항 이용객들에게 불편함을 초래합니다. 팬데믹 이후 공항 이용률이 증가하고 있는 현재, 앞선 문제를 해결하며 공항 이용객의 편의를 향상할 수 있는 새로운 서비스가 필요합니다. 그래서 우리는 갈증을 해소함과 동시에 공항 이용객이 물을 찾아 헤매는 번거로움을 줄일 수 있는 자율주행 물 제공 서비스 로봇을 만들게 되었습니다. 이 제품은 한 모금의 물을 활용하여 간편하게 고객의 니즈를 충족시킬 수 있는 대안을 담고 있습니다.", 
    backgroundImage : 'img/background/background9.png', 
    video : "https://www.youtube.com/embed/aRJSC3eOJCI", 
    profileImage : "img/designer/designer9.jpg" , 
    say : "상상을 현실로 만드는 디자이너가 되고 싶습니다.", 
    Email : "wksehs123@naver.com"},

    {Dname : '황찬영',
    name : 'PATROIBOT', 
    preimage : "img/preview/preview8.png", 
    sub_title: '단속 로봇 <페트로봇>은 스스로 도로를 순회하며 불법 주정차량을 단속하는 자율주행 로봇입니다. 단속 주행 중 그 역할에 순찰 기능을 더하여 도시 내 치안을 담당하게 될 것입니다.', 
    text : '<h4>나날이 증가하는 차량, 함께 증가하는 불법 주정차 차량들.</h4><p>시간이 갈수록 대한민국 가구당 차량 보유 수가 증가하고 있습니다. 하지만 증가하는 차량에 비해서 주차공간은 한정적이며, 그 수가 부족하여 점차 주정차 문제가 증가하고 있습니다. 이러한 사회적 현상 속에서 불법 주정차 문제가 심화되고 있으며, 이는 곧 더 많은 문제를 초래하고 있습니다. 불법 주정차는 다른 차량들과 보행자들의 통행을 방해하는 것은 물론이고, 다른 차량들의 시야를 가려 보행자의 안전을 위협하고 있습니다. 통행 방해는 응급 상황에서의 대처를 불가하게 만들어 중대한 사고를 만들어내고 있습니다.<p/>', 
    background:"복잡한 공항에서 정수기나 물을 구할 곳을 찾아다녀야 하는 번거로움과 보안 검색대를 지나는 과정에서 다 마시지 못한 생수통이 버려지는 문제는 공항 이용객들에게 불편함을 초래합니다. 팬데믹 이후 공항 이용률이 증가하고 있는 현재, 앞선 문제를 해결하며 공항 이용객의 편의를 향상할 수 있는 새로운 서비스가 필요합니다. 그래서 우리는 갈증을 해소함과 동시에 공항 이용객이 물을 찾아 헤매는 번거로움을 줄일 수 있는 자율주행 물 제공 서비스 로봇을 만들게 되었습니다. 이 제품은 한 모금의 물을 활용하여 간편하게 고객의 니즈를 충족시킬 수 있는 대안을 담고 있습니다.", 
    backgroundImage : 'img/background/background10.png', 
    video : "https://www.youtube.com/embed/69w90FRj5lQ", 
    profileImage : "img/designer/designer10.jpg" , 
    say : "아름답기만한 디자인이 아닌 획기적이고 실용적인 디자인을 통해 재미있고 편안한 디자인을 만들어 가겠습니다.", 
    Email : "wksehs123@naver.com"}

]